language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

  # Install grunt.
  - npm install -g grunt-cli
  - npm install -g bower

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # install drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  - phpenv rehash

  - npm install -g yo bower grunt-cli
  - npm install

  # Test the Yeoman generator.
  - npm test

  # Link the generator.
  - npm link

before_script:
  - mkdir ../build
  - cd ../build
  # Initiate the generator to build using CLI. We use the --no-insight flag to
  # prevent yo from waiting for user input about sending anonymous usgae
  # statistics.
  - yo hedley --no-insight --project-name=skeleton --github-repo=https://github.com/Foo/skeleton --db=skeleton --db-user=root --db-pass= --drupal-url=http://127.0.0.1

  # Configure client.
  - cd client
  - cp config.travis.json config.json
  - grunt serve > ~/grunt.log 2>&1 &
  - cd ..

  # Configure Behat.
  - cd behat
  - cp ../../generator-hedley/travis/behat.local.yml.travis behat.local.yml

  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # Start a web server on port 8080, run in the background; wait for
  # initialization.
  - cp ../../generator-hedley/travis/aliases.drushrc.php ~/.drush/
  - drush @site runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # Run selenium.
  - wget http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar
  - java -jar selenium-server-standalone-2.40.0.jar -p 4444 &
  - sleep 5

  # Run PhantomJs.
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

script:
  # Run behat tests.
  - ./bin/behat --tags=~@wip

  # Print log ~/phantomjs.log
  - cat ~/phantomjs.log
