<?php

/**
 * @file
 * Populate dummy GarmentBox content.
 */

/**
 * Implements hook_migrate_api().
 */
function gb_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'GbCompaniesMigrate',
    'GbItemsMigrate',
    'GbItemVariantsMigrate',
    'GbMaterialsMigrate',
    'GbSeasonsMigrate',

    // Terms.
    'GbItemStatusTermsMigrate',
    'GbSeasonStatusTermsMigrate',

    // Users.
    'GbUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
