<?php
/**
 * @file
 * Code for the Skeleton Messages feature.
 */

include_once 'skeleton_messages.features.inc';

/**
 * Implements hook_token_info().
 */
function skeleton_messages_token_info() {
  $info = array();

  $info['tokens']['skeleton']['reset-password-link'] = array(
    'name' => t('Reset Password Link'),
    'description' => t('Display the link for resetting a password.'),
  );

  $info['types']['skeleton'] = array(
    'name' => t('Skeleton'),
    'description' => t('Tokens related to Skeleton.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function skeleton_messages_tokens($type, $tokens, array $data = array(), array $options = array()) {

  $replacements = array();
  if ($type != 'skeleton') {
    return $replacements;
  }

  foreach ($tokens as $name => $original) {
    if (!in_array($name, array('reset-password-link', 'verify-email-link'))) {
      continue;
    }

    $message = reset($data);
    $token = $message->arguments['@token'];

    $path = str_replace('-link', '', $name);

    $options = array(
      'fragment' => $path . '/' . $token,
    );
    $replacements[$original] = url(variable_get('skeleton_default_client_domain', 'http://localhost:9000/'), $options);
  }

  return $replacements;
}
