<?php
/**
 * @file
 * Code for the Skeleton Event feature.
 */

include_once 'skeleton_event.features.inc';

/**
 * Implement hook_node_insert().
 */
function skeleton_event_node_insert($node) {
  if ($node->type != 'event') {
    return;
  }
  $wrapper = entity_metadata_wrapper('node', $node);
  $company_id = $wrapper->{OG_AUDIENCE_FIELD}->value(array('identifier' => TRUE));

  $data = array(
    'userId' => $node->uid,
  );

  skeleton_pusher_trigger_event($company_id, 'new-event', $data);
}
